window:
  decorations: none

scrolling:
  history: 10000

  multiplier: 3

font:
  normal:
    family: Caskaydia Cove
  size: 12.0

colors:
  primary:
    background: '#282828'
    foreground: '#ebdbb2'
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

background_opacity: 0.9

selection:
  save_to_clipboard: false

cursor:
  vi_mode_style: Block

live_config_reload: true

